CREATE TABLE tipo_gasto (
  id BIGINT AUTO_INCREMENT NOT NULL,
   nome VARCHAR(255) NOT NULL,
   user_id BIGINT NULL,
   CONSTRAINT pk_tipo_gasto PRIMARY KEY (id)
);

ALTER TABLE tipo_gasto ADD CONSTRAINT FK_TIPO_GASTO_ON_USER FOREIGN KEY (user_id) REFERENCES usuario (id);