CREATE TABLE transacao (
  id BIGINT AUTO_INCREMENT NOT NULL,
   valor FLOAT NOT NULL,
   dia INT NOT NULL,
   mes INT NOT NULL,
   ano INT NOT NULL,
   gasto_id BIGINT NULL,
   `description` VARCHAR(255) NOT NULL,
   user_id BIGINT NULL,
   CONSTRAINT pk_transacao PRIMARY KEY (id)
);

ALTER TABLE transacao ADD CONSTRAINT FK_TRANSACAO_ON_GASTO FOREIGN KEY (gasto_id) REFERENCES tipo_gasto (id);

ALTER TABLE transacao ADD CONSTRAINT FK_TRANSACAO_ON_USER FOREIGN KEY (user_id) REFERENCES usuario (id);